name: Deploy the static file to GitHub Page
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: deploy docs
      uses: ./
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        remote_url: https://github.com/Rog99/Vaishak-Menon.git